drop table if exists comands, employees CASCADE;

CREATE Table comands
(
    id_ int primary key generated by default as identity,
    name_ text,
    data_ date
);

CREATE Table employees
(
    id_employees int primary key generated by DEFAULT as identity,
    name_employees text,
    sname_employees text,
    job_title_employees text,
    id_ int,
    FOREIGN KEY (id_) REFERENCES comands (id_)
);

INSERT into comands(name_, data_)
VALUES('волшебники', '2024-10-10'),
        ('врачи', '2000-05-02');

INSERT into employees(name_employees, sname_employees, job_title_employees, id_)
VALUES  ('игорь', 'игорев', 'картежник', 1),
        ('гриша', 'григорьев', 'доктор', 2),
        ('вова', 'вовчинко', 'фокусник', 1);
    
SELECT comands.name_, comands.data_, COALESCE(json_agg(json_build_object(
    'имя', name_employees, 'фамилия', sname_employees, 'должность', job_title_employees))
    FILTER(WHERE employees.id_employees is not NULL), '[]')
    from comands
    LEFT JOIN employees on employees.id_ = comands.id_
    GROUP BY comands.id_;
    
    -- Нехорошев Артём
