drop table if exists courier, zakaz;
create table courier
(
	id int primary key
   		 generated  by default as identity,
   	first_name text,
   	last_name text,
   	phone_number text   		 
);

create table zakaz
(
	id int primary key generated by default as identity,
	courier_id  int references courier(id),
	adress text,
	date_reliase date,
	status text
);

insert into courier(first_name, last_name, phone_number)
values ('Олег', 'Брагин', '+7980754389'),
		('Марина', 'Нарочинская', '+79193456789');
	
insert into zakaz(courier_id, adress, date_reliase, status)
values (1, 'Восресенская 12', '2024-02-22', 'собран на складе'),
		(2, 'Воровского 34', '2023-09-09', 'доставлен');
	
select
	co.id,
	co.first_name,
	co.last_name,
	co.phone_number,
	coalesce (json_agg(jsonb_build_object(
	'id', z.id, 'adress', z.adress, 'date_reliase', z.date_reliase, 'status', z.status))
	filter (where z.id is not null), '[]')
from courier co
left join zakaz z
	on co.id = z.courier_id
group by co.id;