drop table if exists providers, vehicles;

create table providers
(
    id int primary key generated by default as identity,
    name text,
    phone_number text
);

create table vehicles
(
    id int primary key generated by default as identity,
    id_provider int references providers(id),
    brand text,
    model text,
    lif_capacity text
);

insert into providers (name, phone_number)
values
    ('A', '+79003352546'),
    ('B', '+79003352546'),
    ('C', '+79003352546');

insert into vehicles (id_provider, brand, model, lif_capacity)
values
    (1, 'OOO', '555', '3 kg'),
    (2, 'AAA', '777', '5 kg'),
    (3, 'TTT', '999', '4 kg');

select
    pro.id,
    pro.name,
    pro.phone_number,
    coalesce(json_agg(json_build_object('brand', ve.brand, 'model', ve.model, 'lif_capacity', ve.lif_capacity))
             filter (where ve.id is not null), '[]') as vehic

from providers as pro
         left join vehicles ve on pro.id = ve.id_provider
group by pro.id;