DROP TABLE IF EXISTS games, feedbacks CASCADE;

CREATE TABLE games (
    id int primary key generated by default as identity,
    name TEXT,
    genre TEXT,
    price INT
);

CREATE TABLE feedbacks (
    id int primary key generated by default as identity,
    text TEXT,
    mark INT,
    game_id INT REFERENCES games(id)
);

INSERT INTO games (name, genre, price) VALUES
('Game1', 'Action', 50),
('Game2', 'Adventure', 60);

INSERT INTO feedbacks (text, mark, game_id) VALUES
('Good game', 5, 1),
('Awesome!', 4, 1);

SELECT
    games.*,
    json_agg(feedbacks.*) AS feedbacks
FROM
    games
LEFT JOIN
    feedbacks ON games.id = feedbacks.game_id
GROUP BY
    games.id;

