DROP TABLE IF EXISTS taxists, orders cascade;

CREATE TABLE taxists (
    id int primary key generated by default as identity unique,
    name text,
    sname text,
    phone text,
    car text
);

CREATE TABLE orders (
    id int primary key generated by default as identity,
    name text,
    date date,
    price int,
    address text,
    endpoint text,
    taxist_id int references taxists
);

INSERT INTO taxists (name, sname, phone, car) VALUES
('1', '2', '3', '4'),
('1', '2', '3', '4');

INSERT INTO orders (name, date, price, address, endpoint, taxist_id) VALUES
('1', '01-02-2022', '3', '4', '5', 1),
('12', '01-02-2022', '3', '4', '5', 1),
('21', '01-02-2022', '3', '4', '5', 2),
('222', '01-02-2023', '3', '4', '6', 2);

select *
from orders
    left join taxists on taxists.id = orders.taxist_id;
