-- . Репозитории и тикеты:
-- репозиторий может иметь несколько тикетов
-- тикет может принадлежать только одному репозиторию
-- репозиторий - название, описание, количество звезд
-- тикет - название, описание, статус

DROP TABLE IF EXISTS repos, tickets cascade;

CREATE TABLE repos (
    id int primary key generated by default as identity unique,
    name text,
    description text,
    stars int
);

CREATE TABLE tickets (
    id int primary key generated by default as identity,
    name text,
    description text,
    status text,
    repos_id int references repos
);

INSERT INTO repos (name, "description", stars) VALUES
('Repo1', 'First', 5),
('Repo2', 'Sec', 4),
('Repo3', 'Sec', 4),
('Repo4', 'Sec', 4),
('Repo5', 'Sec', 4),
('Repo6', 'Th', 1);

INSERT INTO tickets (name, "description", status, repos_id) VALUES
('Repo1', 'Option', 'used', 1),
('Repo1', 'Option2', 'not_used', 2),
('Repo1', 'Option2', 'not_used', 2),
('Repo2', 'Option3', 'not_used', 3);

SELECT *
FROM tickets
LEFT JOIN repos AS t ON tickets.repos_id = t.id;
